name: Build And deploy bookdown

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-deploy-bookdown:
    name: Déploiement de ${{ github.repository }}
    uses: jdlom/parcours-r/.github/workflows/build-bookdown.yml@workflow_reutilisable
    with:
      r_version: '4.0.4'
