name: Image docker parcours_r_socle_preparation_des_donnees

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      -'!**'
      - '.github/workflows/build-rstudio-image.yml'
      - 'Dockerfile'
      - 'renv.lock'
      
  workflow_dispatch:

jobs:
  build-rstudio-image:
    uses: jdlom/parcours-r/.github/workflows/build-rstudio-image.yml@workflow_reutilisable
